---
thema: Titel der Arbeit
schlagworte: Spezifische, Schlagworte, zur, Ausarbeitung
zusammenfassung: Lorem Ipsum
autor: Max Mustermann
ausgabedatum: 01.01.2022
abgabedatum: 01.02.2022
autorStrasse: Musterstrasse 1
autorPLZ: 99999 
autorOrt:  Musterstadt
autorGeburtsort: Musterstadt
autorGeburtsdatum: 01.01.1990
prueferA: Prof. Dr. M. Musterer (TU Berlin)
prueferB: Prof. Dr.  M. Musterin (XXX)
betreuer: Name des Betreuers mit Titel (TU Berlin)
betreuerU: ggf. Name des Betreuers mit Titel (Unternehmen)
firma: TU Berlin
fakultaet: Fahrzeugtechnik
studiengang: Angewandtes Markdown, Vertiefungsrichtung Pandoc


lang: de
bib: true
# table of contents
toc: true 
# list of figures
lof: true
# list of tables
lot: true
documentclass: report
pagenumberstyle_before: Roman
pagenumberstyle_thesis: arabic
mainfont: abc
fontsize: 11pt
geometry: margin=3cm,headsep=.5cm,headheight=.5cm
papersize: a4paper
fontfamily: libertine

# color of reference links and online urls, uncomment if u want them to be black, or change to any color u want
# linkcolor: black 
# urlcolor: black

# References as link to the corresponding entry in the bibliography
# link-citations: true
---

